---
- name: Update host data
  freeipa.ansible_freeipa.ipahost:
    ipaadmin_password: "{{ rhidm_admin_password }}"
    name: "{{ item }}"
    description: "{{ __description | trim if __description != 'na' else omit }}"
    userclass: "{{ __userclass | trim if __userclass != 'na' else omit}}"
    state: present
  vars:
    __userclass: "{{ hostvars[item].host_userclass | default('na') }}"
    __description: "{{ hostvars[item].host_description | default('na') }}"
  loop: "{{ groups['rhidm_clients'] }}"
  tags:
    - update_hostdata

- name: Manage the host groups
  freeipa.ansible_freeipa.ipahostgroup:
    ipaadmin_principal: "{{ rhidm_admin_principal }}"
    ipaadmin_password: "{{ rhidm_admin_password }}"
    name: "{{ item.name }}"
    description: "{{ item.description | trim }}"
    host: "{{ item.host | default(omit) }}"
    hostgroup: "{{ item.hostgroup | default(omit) }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ rhidm_hostgroups }}"
  loop_control:
    label: "{{ item.name }} - {{ item.state | default('present') }}"

- name: Build the automember variables
  ansible.builtin.set_fact:
    rhidm_group_auto_member: "{{ lookup('template', 'templates/automember_rules_hosts.yml.j2') | from_yaml }}"
  tags:
    - rhidm_config_group_auto_member

- import_tasks: manage_automember.yml
