---
## Handlers for the automembers
## When an AM rule is created we rebuild the membership so as existing users are
## updated too

- name: Rebuild User Group membership
  freeipa.ansible_freeipa.ipaautomember:
    ipaadmin_password: "{{ rhidm_admin_password }}"
    automember_type: "group"
    state: "rebuilt"
  listen: "Rebuild Automember"
  tags:
    - rhidm_config_group_auto_member
